backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    delete: false
    files:
      - file: src/pages/index.md
        label: Index
        name: index
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: index-page,
            }
          - {
              label: Meta,
              name: meta,
              widget: object,
              fields:
                [
                  { label: Meta Title, name: metaTitle, widget: string },
                  {
                    label: Meta Description,
                    name: metaDescription,
                    widget: text,
                  },
                ],
            }
          - { label: Title, name: title, widget: string }
      - file: src/pages/bio/index.md
        label: Bio
        name: bio
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: bio-page,
            }
          - {
              label: Meta,
              name: meta,
              widget: object,
              fields:
                [
                  { label: Meta Title, name: metaTitle, widget: string },
                  {
                    label: Meta Description,
                    name: metaDescription,
                    widget: text,
                  },
                ],
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: src/pages/cv/index.md
        label: CV Page
        name: cv
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: cv-page,
            }
          - {
              label: Meta,
              name: meta,
              widget: object,
              fields:
                [
                  { label: Meta Title, name: metaTitle, widget: string },
                  {
                    label: Meta Description,
                    name: metaDescription,
                    widget: text,
                  },
                ],
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        {
                          label: Address,
                          name: address,
                          widget: markdown,
                          buttons: [bold, italic, link],
                        },
                        { label: email, name: email, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Employment,
              name: employment,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Year, name: year, widget: string },
                        {
                          label: Institution,
                          name: institution,
                          widget: string,
                        },
                        {
                          label: Institution Location,
                          name: institutionLocation,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Education,
              name: education,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Year, name: year, widget: string },
                        {
                          label: Institution,
                          name: institution,
                          widget: string,
                        },
                        {
                          label: Institution Location,
                          name: institutionLocation,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Interests,
              name: interests,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [{ label: Interest, name: interest, widget: string }],
                  },
                ],
            }
          - {
              label: Publications,
              name: publications,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        {
                          label: Quoted Title?,
                          name: quotes,
                          widget: boolean,
                          default: true,
                        },
                        { label: Year, name: year, widget: string },
                        { label: Journal, name: journal, widget: string },
                        {
                          label: Journal Issue,
                          name: journalIssue,
                          widget: string,
                        },
                        { label: Co-author, name: coAuthor, widget: string },
                        { label: Award, name: award, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Papers In Progress,
              name: papersInProgress,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        {
                          label: Quoted Title?,
                          name: quotes,
                          widget: boolean,
                          default: true,
                        },
                        { label: Year, name: year, widget: string },
                        { label: Co-author, name: coAuthor, widget: string },
                        { label: Status, name: status, widget: markdown },
                      ],
                  },
                ],
            }
          - {
              label: Funding,
              name: funding,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        {
                          label: Institution,
                          name: institution,
                          widget: string,
                        },
                        { label: Amount, name: amount, widget: string },
                        { label: Year, name: year, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Awards,
              name: awards,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        { label: Year, name: year, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Conference Presentations,
              name: conferencePresentations,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Conference, name: conference, widget: string },
                        { label: Location, name: location, widget: string },
                        { label: Title, name: title, widget: text },
                        {
                          label: Quoted Title?,
                          name: quotes,
                          widget: boolean,
                          default: true,
                        },
                        { label: Year, name: year, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Campus Presentations,
              name: campusPresentations,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        {
                          label: Quoted Title?,
                          name: quotes,
                          widget: boolean,
                          default: true,
                        },
                        { label: Year, name: year, widget: string },
                        { label: Event, name: event, widget: string },
                        {
                          label: Institution,
                          name: institution,
                          widget: string,
                        },
                        {
                          label: Institution Location,
                          name: institutionLocation,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Teaching Experience,
              name: teachingExperience,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Semester, name: semester, widget: string },
                        { label: Title, name: title, widget: string },
                        {
                          label: Courses,
                          name: courses,
                          widget: list,
                          fields:
                            [{ label: Course, name: course, widget: string }],
                        },
                        {
                          label: Institution,
                          name: institution,
                          widget: string,
                        },
                        {
                          label: Institution Location,
                          name: institutionLocation,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Professional Development,
              name: professionalDevelopment,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Subtitle, name: subTitle, widget: string },
                        { label: Year, name: year, widget: string },
                        {
                          label: Institution,
                          name: institution,
                          widget: string,
                        },
                        {
                          label: Institution Location,
                          name: institutionLocation,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Affiliations,
              name: affiliations,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        {
                          label: Organization,
                          name: organization,
                          widget: string,
                        },
                        { label: Title, name: title, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Media,
              name: media,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        {
                          label: Quoted Title?,
                          name: quotes,
                          widget: boolean,
                          default: true,
                        },
                        { label: Year, name: year, widget: string },
                        {
                          label: Organization,
                          name: organization,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Pro Service,
              name: proService,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        {
                          label: Title,
                          name: title,
                          widget: markdown,
                          buttons: [bold, italic, link],
                        },
                        { label: Year, name: year, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: University Service,
              name: universityService,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        {
                          label: Title,
                          name: title,
                          widget: markdown,
                          buttons: [bold, italic, link],
                        },
                        { label: Year, name: year, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Department Service,
              name: departmentService,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        {
                          label: Title,
                          name: title,
                          widget: markdown,
                          buttons: [bold, italic, link],
                        },
                        { label: Year, name: year, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Public Service,
              name: publicService,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        { label: Year, name: year, widget: text },
                        { label: Location, name: location, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: References,
              name: references,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: Email, name: email, widget: string },
                      ],
                  },
                ],
            }
